/* Shared, public Scripture catalogue. No personal journal data belongs here.
   Context/related passages are editorial teaching aids, not quotations or an official concordance. */
(function(root){'use strict';
const rows=[
 ['luke-22-42','Luke 22:42','Luke','Will',['W'],['Pray','Learn','About'],'Jesus brings his request to the Father and submits to the Father’s will.',['matthew-26-37-39','romans-12-1-2'],'Luke.22.42','luk/22'],
 ['psalm-139-23-24','Psalm 139:23-24','Psalms','Heart',['H'],['Pray','Learn','About'],'The psalmist invites God to examine him and lead him.',['ezra-7-10','romans-12-1-2'],'Ps.139.23','psa/139'],
 ['matthew-26-37-39','Matthew 26:37-39','Matthew','Emotions',['E','W'],['Pray','Learn','About'],'Jesus experiences deep sorrow while praying in submission to his Father. Distress is not itself disobedience.',['luke-22-42','philippians-4-6-7'],'Matt.26.38','mat/26'],
 ['romans-12-1-2','Romans 12:1-2','Romans','Mind',['M','W'],['Pray','Learn','About'],'Paul connects a life offered to God with renewed thinking and discernment.',['james-1-5','ezra-7-10'],'Rom.12.2','rom/12'],
 ['ephesians-2-8-10','Ephesians 2:8-10','Ephesians','Soul',['S'],['Pray','Learn','About'],'Salvation is God’s gift by grace through faith; good works follow rather than earn it.',['romans-6-17-23','john-8-34-36'],'Eph.2.8','eph/2'],
 ['romans-6-17-23','Romans 6:17-23','Romans','Soul',['S'],['Pray','Learn','About'],'Paul describes freedom from sin’s mastery as a new allegiance to righteousness and to God.',['ephesians-2-8-10','john-8-34-36'],'Rom.6.22','rom/6'],
 ['john-8-34-36','John 8:34-36','John','Soul',['S'],['Learn'],'Jesus speaks about slavery to sin and the freedom that the Son gives.',['romans-6-17-23','ephesians-2-8-10'],'John.8.36','jhn/8'],
 ['philippians-4-6-7','Philippians 4:6-7','Philippians','Prayer and thanksgiving',['W','H','E','M','S'],['Pray','Journal','Learn','About'],'Paul brings requests and thanksgiving together in prayer. The text does not make a feeling of calm an approval of every choice.',['james-1-5','matthew-26-37-39'],'Phil.4.6','phl/4'],
 ['james-1-5','James 1:5','James','Wisdom',['M'],['Pray','Learn'],'In the setting of trials, James directs those who lack wisdom to ask God.',['proverbs-15-22','romans-12-1-2'],'Jas.1.5','jas/1'],
 ['proverbs-15-22','Proverbs 15:22','Proverbs','Counsel',['M'],['Pray','Learn'],'This proverb commends counsel rather than isolated planning. It is wisdom to apply, not a guarantee for a preferred outcome.',['james-1-5','romans-12-1-2'],'Prov.15.22','pro/15'],
 ['galatians-5-22-25','Galatians 5:22-25','Galatians','Fruit of the Spirit',['W','H','E','M','S'],['Pray','Learn','About'],'Paul names the Spirit’s fruit and calls believers to keep in step with the Spirit. These concern our character, not a forecast of success.',['romans-12-1-2','ephesians-2-8-10'],'Gal.5.22','gal/5'],
 ['acts-13-22','Acts 13:22','Acts','Biblical examples',['H','W'],['About'],'Paul’s account recalls God’s assessment of David and his willingness to carry out God’s purposes.',['psalm-139-23-24','ezra-7-10'],'Acts.13.22','act/13'],
 ['1samuel-1-15','1 Samuel 1:15','1 Samuel','Biblical examples',['E','S'],['About'],'Hannah describes pouring out her soul before the Lord. Her distress belongs in prayer.',['philippians-4-6-7','matthew-26-37-39'],'1Sam.1.15','1sa/1'],
 ['daniel-1-8','Daniel 1:8','Daniel','Biblical examples',['W'],['About'],'Daniel resolves not to defile himself and asks permission concerning his food.',['luke-22-42','romans-12-1-2'],'Dan.1.8','dan/1'],
 ['ezra-7-10','Ezra 7:10','Ezra','Biblical examples',['H','M','W'],['About'],'Ezra sets his heart to study, practise and teach God’s Law. Biblical heart-language includes more than feeling.',['romans-12-1-2','psalm-139-23-24'],'Ezra.7.10','ezr/7']
];
const books=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'];
const normal=s=>String(s||'').replace(/\+/g,' ').replace(/\u2013/g,'-').replace(/\s+/g,' ').trim().toLowerCase();
const items=rows.map(([id,ref,book,topic,areas,used,context,related,step,blb])=>Object.freeze({id,ref,book,topic,areas,used,context,related,esv:'https://www.esv.org/verses/'+encodeURIComponent(ref).replace(/%20/g,'+').replace(/%3A/g,':')+'/',step:'https://www.stepbible.org/?q='+encodeURIComponent('version=ESV|reference='+step),blb:'https://www.blueletterbible.org/esv/'+blb+'/'}));
function get(id){return items.find(x=>x.id===id)||null;}
function byReference(ref){return items.find(x=>normal(x.ref)===normal(ref))||null;}
function fromURL(url){try{const u=new URL(url);if(!['www.esv.org','esv.org'].includes(u.hostname))return null;return byReference(decodeURIComponent(u.pathname.replace(/^\/verses\//,'').replace(/^\//,'').replace(/\/$/,'')));}catch{return null;}}
function filter(query='',topic='',order='book'){const q=normal(query);return items.filter(x=>(!topic||x.topic===topic||x.areas.includes(topic))&&normal([x.ref,x.topic,...x.used,...x.areas].join(' ')).includes(q)).sort((a,b)=>order==='book'?books.indexOf(a.book)-books.indexOf(b.book)||a.ref.localeCompare(b.ref,undefined,{numeric:true}):a.topic.localeCompare(b.topic)||a.ref.localeCompare(b.ref));}
const api={items,get,byReference,fromURL,filter,books};if(typeof module==='object'&&module.exports)module.exports=api;else root.WholeheartedScripture=api;
})(globalThis);
