/* Contextual guide contracts. No network calls or storage in this module. */
(function(root){'use strict';
const C=typeof module==='object'&&module.exports?require('./core.js'):root.WholeheartedCore;
const S=typeof module==='object'&&module.exports?require('./catalogue.js'):root.WholeheartedScripture;
const text=(x,n=3000)=>typeof x==='string'?x.slice(0,n):'';
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const keys=['W','H','E','M','S'];
function state(raw){const x=object(raw)?raw:{};if(Array.isArray(x.turns)&&x.turns.length>12)throw Error('This entry has reached its guidance-history limit. Its saved data has not been replaced.');return {issue:text(x.issue,4000),context:text(x.context,4000),replies:Object.fromEntries(keys.map(k=>[k,text(x.replies?.[k],2000)])),voice:x.voice==='community'?'community':'personal',summaryConfirmed:x.summaryConfirmed===true,summary:text(x.summary,2500),result:object(x.result)?validateGuide(x.result):null,turns:Array.isArray(x.turns)?x.turns.slice(-12).map(t=>({at:text(t.at,40),summary:text(t.summary,2000),replies:Object.fromEntries(keys.map(k=>[k,text(t.replies?.[k],2000)])),questions:Object.fromEntries(keys.map(k=>[k,text(t.questions?.[k],2000)]))})):[],generatedAt:text(x.generatedAt,40),model:text(x.model,100)};}
function forms(raw){const x=object(raw)?raw:{};return {sentence:text(x.sentence,6000),whems:text(x.whems,16000),extended:text(x.extended,24000),origin:text(x.origin,100),at:text(x.at,40)};}
function strings(x,max=8){if(!Array.isArray(x)||x.length>max||x.some(t=>typeof t!=='string'||t.length>2000))throw Error('The guidance response was not complete. Please retry.');return x;}
function refs(x){const a=strings(x,8);if(a.some(id=>!S.get(id)))throw Error('A Scripture reference could not be verified.');return [...new Set(a)];}
function validateGuide(x){if(!object(x)||typeof x.summary!=='string'||x.summary.length>2500||!Array.isArray(x.areas)||x.areas.length!==5)throw Error('The guidance response was incomplete.');
 const seen=new Set();const areas=x.areas.map(a=>{if(!object(a)||!keys.includes(a.key)||seen.has(a.key)||!['focus','question','followup'].every(k=>typeof a[k]==='string'&&a[k].length<1800))throw Error('The five guidance areas could not be verified.');seen.add(a.key);return {key:a.key,focus:a.focus,question:a.question,followup:a.followup,referenceIds:refs(a.referenceIds)};});
 if(!Array.isArray(x.options)||x.options.length>4)throw Error('Decision options could not be verified.');
 return {summary:x.summary,statedFacts:strings(x.statedFacts),uncertainties:strings(x.uncertainties),clarification:text(x.clarification,2000),areas:keys.map(k=>areas.find(a=>a.key===k)),options:x.options.map(o=>{if(!object(o)||!['action','reason','caution'].every(k=>typeof o[k]==='string'&&o[k].length<2000))throw Error('Decision options could not be verified.');return {action:o.action,reason:o.reason,caution:o.caution,referenceIds:refs(o.referenceIds)};}),safetyNote:text(x.safetyNote,1800)};
}
function validatePrayers(x){if(!object(x)||!['sentence','whems','extended'].every(k=>typeof x[k]==='string'&&x[k].trim()&&x[k].length<24000))throw Error('All three prayer forms were not returned. Your earlier wording has been kept.');
 if(!keys.every(k=>new RegExp('(?:^|\\n)'+k+'\\s*[-–:.]').test(x.whems)))throw Error('The W.H.E.M.S. prayer did not include all five labelled areas.');
 if(x.extended.trim().split(/\s+/).length<300)throw Error('The extended prayer was incomplete. Please retry or use the local drafts.');
 return forms({...x,origin:'AI-assisted draft',at:new Date().toISOString()});}
function payload(d,action){const g=state(d.journey);return {action,consent:true,issue:g.issue,context:g.context,summary:g.summaryConfirmed?g.summary:'',replies:g.replies,questions:Object.fromEntries(keys.map(k=>[k,g.result?.areas.find(a=>a.key===k)?.question||''])),voice:g.voice,belonging:d.belonging||'',entryType:d.entryType,areas:Object.fromEntries(keys.map(k=>{const a=d.areas[k];return [k,{thank:a.thank,ask:a.ask,thankNote:a.thank?a.thankNote:'',askNote:a.ask?a.askNote:''}];})),nextStep:d.nextStep||'',fruit:d.fruit||[]};}
function local(d){const g=state(d.journey),we=g.voice==='community',our=we?'our':'my',us=we?'us':'me',I=we?'we':'I';
const issue=g.issue.trim()||d.context.trim()||d.topic.trim()||'this matter';
const thanks=C.AREAS.filter(a=>d.areas[a.key].thank).map(a=>d.areas[a.key].thankNote.trim()||a.thank);
const asks=C.AREAS.filter(a=>d.areas[a.key].ask).map(a=>d.areas[a.key].askNote.trim()||a.ask);
const sentence=`Father, ${thanks.length?'thank you for '+thanks.join('; '):I+' bring '+issue+' before you'}; ${asks.length?'please help '+us+' with '+asks.join('; '):'give '+us+' wisdom, love and willingness to obey'}, so that ${our} decision and response honour Christ.`;
const whems=C.AREAS.map(a=>{const r=d.areas[a.key];return `${a.key} - ${a.name}\n`+(r.thank?`Father, thank you for ${r.thankNote.trim()||a.thank}. `:'')+(r.ask?`Please help ${us}: ${r.askNote.trim()||a.ask}. `:'')+(!r.ask&&!r.thank?`Father, help ${us} ${a.ask}. `:'')+(g.replies[a.key]?`As ${I} reflect, ${I} bring these words before you: ${g.replies[a.key]}`:'');}).join('\n\n')+`\n\nHelp ${us} honour Christ and entrust the outcome to you. In Jesus’ name, amen.`;
const extended=[`Holy and gracious Father, you are wise where ${I} see only a little, faithful when circumstances change, and good beyond ${our} ability to measure. ${we?'We come':'I come'} before you without a claim to deserve your favour. Turn ${our} attention from the demand to secure every outcome towards your character, your Word and the mercy you reveal in Jesus Christ. Teach ${us} to approach you with reverence, honesty and hope.`,
`Through Jesus Christ, ${I} seek mercy and help. Let the cross remind ${us} of the seriousness of sin and the greatness of your grace. Let his resurrection direct ${our} hope beyond present limitations. By your Holy Spirit, make this prayer more than careful language: shape ${our} desires, renew ${our} understanding and strengthen ${us} to respond with love. ${d.belonging==='exploring'?'Help '+us+' understand what it means to trust Jesus rather than pretending to a certainty not yet expressed.':''}`,
`Here is the matter ${I} bring before you: ${issue}. ${g.context?'These circumstances also concern '+us+': '+g.context+'. ':''}You know what has been said and what remains unknown. Keep ${us} from confusing an assumption with a fact, or a strong feeling with your command. Give ${us} patience to listen, humility to ask, and courage to consider information that may correct ${our} first understanding.`,
thanks.length?`Father, ${I} give thanks for ${thanks.join('; ')}. Receive this gratitude without letting ${us} pretend that every difficulty is resolved. Teach ${us} to notice help received through Scripture, ordinary care, faithful counsel and strength to persevere. Let thanksgiving deepen dependence on you rather than confidence in ${our} own judgement.`:`Thank you that this uncertainty can be brought honestly before you. Thank you for your Word, for the invitation to pray and for the help found in the life of your people. Open ${our} eyes to mercies ${I} may overlook. Keep ${us} from claiming an answer that has not been received, and teach ${us} to give thanks without disguising unresolved questions.`,
`Search ${our} heart, Lord. Where pride, selfishness or unwillingness to obey is present, expose it and grant repentance. Do not let ${us} manufacture accusations against ${we?'ourselves':'myself'} or others, but do not let ${us} avoid a correction your Word truly requires. Make ${our} love patient and sincere. Distinguish rightful responsibility from the desire to control what belongs to another person or to your providence.`,
`In ${our} will, teach obedience; in ${our} heart, grow love; in ${our} emotions, receive what is painful and shape ${our} response; in ${our} mind, renew understanding; and in ${our} whole life, deepen faithful allegiance to Christ. ${asks.length?'In particular, please help '+us+' with '+asks.join('; ')+'. ':''}Give appropriate care to the people affected, without making ${us} assume their thoughts, wishes or spiritual condition.`,
`${d.nextStep?'As '+I+' consider this next step - '+d.nextStep+' - correct what is unwise and strengthen what is faithful.':'Show '+us+' the next responsible step, without letting the desire for certainty become an excuse to neglect what is already clear.'} Grow ${d.fruit?.length?d.fruit.map(x=>x.toLowerCase()).join(', '):'love, patience, gentleness and self-control'} in the way ${I} act. Sustain ${us} when waiting is necessary, and provide suitable human counsel when this matter exceeds ${our} knowledge.`,
`Finally, Father, ${I} entrust the outcome to you. Neither success nor disappointment can make ${us} master of your purposes. Keep ${us} teachable, grateful and ready to return with further requests. Let ${our} words and actions honour Jesus, and let whatever help is received become an occasion for humble thanksgiving. To you be glory through Jesus Christ, in whose name ${I} pray. Amen.`].join('\n\n');
return forms({sentence,whems,extended,origin:'Local structured draft - no AI',at:new Date().toISOString()});}
const api={state,forms,validateGuide,validatePrayers,payload,local,keys};if(typeof module==='object'&&module.exports)module.exports=api;else root.WholeheartedGuidance=api;
})(globalThis);
