/* The open W.H.E.M.S. workspace. Only explicit AI buttons send the current issue. */
(function(root){'use strict';const G=root.WholeheartedGuidance,C=root.WholeheartedCore,UX=root.WholeheartedExperience;
let host=null,busy=false,controller=null,lastUI=null,quickAt=0;
const P=root.WholeheartedPrayerOutput,candidates=new WeakMap();const consents={pray:false,journal:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={sentence:'One-sentence prayer',whems:'W.H.E.M.S. prayer',extended:'Extended prayer'};
/* Only the acronym is kept from browser translation; every other word stays translatable. */
const guard=s=>esc(s).replace('W.H.E.M.S.','<span translate="no">W.H.E.M.S.</span>');
const NEXT={W:'H',H:'E',E:'M',M:'S'};
/* doc/background.MD section 23 in plain words. Static text: nothing is fetched. */
const HELP=['Someone is in immediate danger.','Someone may harm themselves or another person.','Abuse is happening.','Someone is being forced or pressured (coercion).','Serious medical symptoms.','Legal deadlines.','Large money decisions that cannot be undone.','Keeping children or vulnerable adults safe (safeguarding).','A situation that needs emergency services.','A matter that needs advice from a trained professional.'];
const aiState=()=>consents.pray?'AI help is on (you agreed above).':'AI help is off.';
const starters={W:['What action are you considering, and what would it seek to accomplish?','What would make it difficult to change your preferred response?'],H:['What good are you hoping for, and for whom?','What motives do you recognise? Do not assume that every desire is wrong.'],E:['What are you feeling, and what have other people actually expressed?','How might your feelings affect your response without deciding what is true?'],M:['What do you know, and what are you presently assuming?','What context, Scripture or wise counsel could change your understanding?'],S:['How does your relationship with Christ bear on this matter?','What responsibility is yours, and what outcome must you entrust to God?']};
const care={
W:['Where has God helped you become willing?','Where do you need help to act faithfully?'],
H:['What love or concern can you give thanks for?','What desires would you bring before God?'],
E:['What comfort or patience have you received?','What feeling or response needs help?'],
M:['What has become clearer?','Where do you still need wisdom?'],
S:['What grace or hope can you give thanks for?','What do you need to entrust to God?']};
const starts={
 W:'Lord, help me become willing to do what honours you, even while I am uncertain.',
 H:'Lord, search what I desire and help me seek the good of those affected.',
 E:'Lord, I bring you what I feel; help me respond with patience and gentleness.',
 M:'Lord, help me understand what is true and recognise what I still need to learn.',
 S:'Lord, help me understand your grace in Christ and entrust my life to you.'};
function area(a,d,g,r,u){
 const q=r?.areas.find(x=>x.key===a.key),v=d.areas[a.key],question=esc(q?.question||starters[a.key][0]);
 return `<section class="area open-area" id="reflection-${a.key}" data-toc-label="${a.key} - ${a.name}" data-area="${a.key}"><h2><span class="area-mark" translate="no" aria-hidden="true">${a.key}</span>${a.name}</h2><div data-context-focus="${a.key}">${q?'<p class="guidance-source">Questions shaped around your issue</p><p class="context-focus"><strong>What we are considering:</strong> '+esc(q.focus)+'</p>':''}</div><h3 id="question-${a.key}" class="reply-question">${question}</h3><label class="field reply-field"><span id="reply-label-${a.key}">${q?'My answer to this question':'My answer'}</span><textarea id="guidance-reply-${a.key}" aria-labelledby="question-${a.key} reply-label-${a.key}" data-guide-reply="${a.key}" rows="3" maxlength="2000" placeholder="${question}">${esc(g.replies[a.key])}</textarea></label><details class="question-help"><summary>Help with this question</summary><p>${esc(a.help)}</p><p data-context-followup="${a.key}">${esc(q?.followup||starters[a.key][1])}</p><p class="suggested-opening"><strong>An optional starting sentence:</strong> ${esc(starts[a.key])}</p></details>${a.key==='S'?`<p>This is not a test or a score. A struggle does not decide whether you are saved.</p><label class="field">How should the prayer speak about your faith?<select data-field="belonging">${u.options({'':'Do not assume my faith',trusting:'I am trusting Christ',exploring:'I am exploring faith in Christ',private:'Leave this personal'},d.belonging)}</select></label>`:''}<div class="reflection-columns">${['thank','ask'].map(t=>`<div><label class="check reflection-choice"><input type="checkbox" data-field="areas.${a.key}.${t}" ${v[t]?'checked':''}><span><strong>${t==='thank'?'Give thanks for this in my prayer':'Ask for help with this in my prayer'}</strong><small>${esc(care[a.key][t==='thank'?0:1])}</small></span></label><div class="area-note" data-note="${a.key}-${t}" ${v[t]?'':'hidden'}>${u.field('areas.'+a.key+'.'+t+'Note',t==='thank'?'Father, thank you for…':'Father, please help me…',v[t+'Note'],(q?'In this situation, ':'')+(t==='thank'?'I can thank you for…':'please help me with…'),3)}</div></div>`).join('')}</div><div class="reading-links" data-context-references="${a.key}">${(q?.referenceIds.length?q.referenceIds:[u.byReference(a.passage).id]).map(u.ref).join('')}</div><div class="area-next"><p class="meta">You can skip this question.</p><div class="actions">${NEXT[a.key]?`<button type="button" class="secondary" data-locate="#reflection-${NEXT[a.key]} h2">Next: ${C.AREAS.find(x=>x.key===NEXT[a.key]).name}</button>`:`<button type="button" class="secondary" data-locate="#guide-decision h2">Next: choosing your next step</button>`}<button type="button" class="quiet" data-locate="#guide-prayers h2">Go to my prayers</button></div></div></section>`;
}
function render(d,u){lastUI=u;const g=G.state(d.journey),forms=G.forms(d.prayerForms),r=g.result;
return `<div data-editor="pray" class="guided-workspace"><div class="page-heading"><h1 tabindex="-1">Bring the whole matter before God.</h1></div>
${root.WholeheartedTeaching.content('intro')}
<section class="writing-paper issue-paper" id="guide-issue" data-toc-label="Your issue"><div class="issue-grid"><div class="issue-main"><h2 class="issue-question">What is happening, and what are you trying to decide?</h2><label class="field">Your words (one or two sentences is enough)<textarea id="guidance-issue" data-journey="issue" rows="4" maxlength="4000" placeholder="For example: Should I speak to my daughter about her studies, or wait and pray?">${esc(g.issue)}</textarea></label><p class="meta save-promise">Your words stay only on this page until you tap Save.</p></div><div class="path-choice" role="group" aria-label="What would you like to do now?"><button type="button" id="quick-pray" data-quick-pray class="primary">Pray with what I have written</button><p class="meta">Makes three prayers on this device. Nothing is sent.</p><button type="button" class="secondary" data-locate="#go-deeper h2">Go deeper in each area</button><p class="meta">Optional. Five short questions first. You can skip any of them.</p></div></div><details class="help-elsewhere"><summary>When to get other help as well</summary><p>Please do not rely on this page alone when:</p><ul>${HELP.map(t=>'<li>'+t+'</li>').join('')}</ul><p>Prayer is still right. It does not remove the duty to get help.</p></details><label class="field">Anything else that helps explain it? (optional)<textarea data-journey="context" maxlength="4000" rows="3" placeholder="What has actually been said? What is still uncertain? Leave out names and details you do not need to share.">${esc(g.context)}</textarea></label>
<div class="consent-box" id="guide-consent" data-toc-label="AI help (optional)"><h3>Ask AI to help (optional)</h3><p>You do not need AI to pray. If you tick the box, this website sends your issue, the extra details, the replies you have written, the thanksgiving and request notes you have chosen and your next step to OpenAI. It does not send your journal, hidden notes or earlier entries.</p><p>AI is a writing aid. It is not therapy and not a message from God.</p><p>This website does not keep your request, and it asks OpenAI not to store the answer. OpenAI may still keep some data under its own rules, so we cannot promise that nothing is kept.</p><label class="check"><input id="guidance-consent" type="checkbox" data-guidance-consent ${consents.pray?'checked':''}><span>I agree to send the current issue and replies for AI guidance.</span></label><div class="actions"><button type="button" id="guide-reflect-start" data-guide-action="reflect" class="secondary">${r?'Update the AI questions from my replies':'Ask AI to help me think it through'}</button><button type="button" data-guide-action="cancel">Cancel AI request</button><button type="button" class="quiet" data-locate="#guide-prayers h2">Go to my prayers</button></div><p class="meta">Without the tick, nothing is sent.</p></div></section>
<div id="guide-understanding-slot">${r?`<section class="callout interpretation" id="guide-understanding" data-toc-label="Check the AI summary"><h2>Is this a fair summary?</h2><p class="meta">Written by AI (${esc(g.model)}). Correct it before you rely on it.</p><label class="field">The summary in my words<textarea id="guidance-summary" rows="3" data-journey="summary" maxlength="2500">${esc(g.summary)}</textarea></label><label class="check"><input id="guidance-confirm" type="checkbox" data-journey-confirm ${g.summaryConfirmed?'checked':''}><span>This describes my concern, with any corrections above.</span></label><div class="facts-grid"><div><h3>What you told us</h3>${r.statedFacts.map(t=>'<p>'+esc(t)+'</p>').join('')||'<p>No other facts were noted.</p>'}</div><div><h3>Still to understand</h3>${r.uncertainties.map(t=>'<p>'+esc(t)+'</p>').join('')||'<p>The AI noted nothing else as uncertain. Check this yourself.</p>'}</div></div>${r.clarification?'<p><strong>Begin here:</strong> '+esc(r.clarification)+'</p>':''}${r.safetyNote?'<p class="safety-note">'+esc(r.safetyNote)+'</p>':''}</section>`:''}</div>
<section class="areas-intro" id="go-deeper"><h2>Go deeper in each area</h2><p>Five short questions: Will, Heart, Emotions, Mind and Soul. Answer any you like and skip the rest.</p><nav class="whems-jumps" aria-label="Jump to an area">${C.AREAS.map(a=>`<a href="#reflection-${a.key}" data-guide-jump="${a.key}"><span translate="no">${a.key}</span> ${a.name}</a>`).join('')}</nav></section>
<section class="open-whems" aria-label="Five open W.H.E.M.S. reflections">${C.AREAS.map(a=>area(a,d,g,r,u)).join('')}</section>
<div class="actions"><button type="button" id="guide-reflect-followup" data-guide-action="reflect" class="secondary">Ask AI to reflect on my answers</button></div>
<section class="writing-paper decision-paper" id="guide-decision" data-toc-label="Choosing your next step"><h2>Choosing your next step</h2><p>These are considerations, not a divine verdict. You can remain uncertain and still pray.</p><div id="guide-options">${r?.options.map(o=>`<article class="decision-option"><h3>${esc(o.action)}</h3><p><strong>Reason to consider:</strong> ${esc(o.reason)}</p><p><strong>Be careful about:</strong> ${esc(o.caution)}</p><div class="reading-links">${o.referenceIds.map(u.ref).join('')}</div></article>`).join('')||'<p>Think about what Scripture makes clear, what you still do not know, who is affected, and whether you need wise advice.</p>'}</div>${u.field('advice','My thoughts (optional)',d.advice,'What seems wise? What is still uncertain?')}${u.field('nextStep','The next step I choose',d.nextStep,'For example: ask whether a listening conversation would help, rather than assuming advice is wanted.')}<details><summary>Bible passage and the fruit of the Spirit (optional)</summary>${u.field('scripture','Passage and what it teaches',d.scripture)}<div class="attached-refs">${d.referenceIds.map(u.ref).join('')}</div>${u.btn('scripture','Read the Scripture index')}<div class="fruits">${C.FRUIT.map(f=>`<label class="check"><input type="checkbox" data-fruit="${f}" ${d.fruit.includes(f)?'checked':''}><span>${f}</span></label>`).join('')}</div>${u.ref('galatians-5-22-25')}</details></section>
${root.WholeheartedTeaching.content('guardrails')}
${root.WholeheartedTeaching.content('summary')}
<section class="writing-paper final-prayers" id="guide-prayers" data-toc-label="Your three prayers"><h2>Your three prayers</h2><p>The same concern in three forms. A longer prayer is not a stronger prayer.</p><div class="actions"><button type="button" class="quiet" data-locate="#guidance-issue">Change what I wrote</button></div><label class="field">Who is praying?<select data-guide-voice><option value="personal" ${g.voice==='personal'?'selected':''}>Just me (I, my)</option><option value="community" ${g.voice==='community'?'selected':''}>Together (we, our)</option></select></label><p class="principle">Scripture is the authority. These drafts help you pray; they are not a message from God.</p><div class="actions"><button type="button" data-guide-action="local" class="primary">Pray with what I have written (nothing is sent)</button><button type="button" id="guide-prayers-ai" data-guide-action="prayers" class="secondary">Ask AI to write my three prayers</button><button type="button" data-guide-action="historic" class="quiet">Read classic prayers first</button></div><p id="ai-state" class="meta" role="status" aria-live="polite">${aiState()}</p><div class="actions"><button type="button" class="quiet" data-locate="#guidance-consent">Go to the AI permission box</button></div><p class="meta">For shared prayer, remove private details before you share. Read every prayer before you use it aloud.</p><div id="prayer-flow-status" class="prayer-flow-status" role="status" aria-live="polite" hidden></div><div id="three-prayer-forms">${Object.entries(label).map(([k,l])=>`<section class="prayer-form-block" id="prayer-${k}" data-toc-label="${l}" data-prayer-kind="${k}"><h3>${guard(l)}</h3><div class="prayer-form-feedback" data-form-feedback="${k}" role="status">${feedbackHTML(d,k)}</div><label class="field">Edit ${k==='sentence'?'the sentence':k==='whems'?'the <span translate="no">W.H.E.M.S.</span> prayer':'the extended prayer'}<textarea data-prayer-form="${k}" rows="${k==='sentence'?3:k==='whems'?12:18}" maxlength="24000" placeholder="Your prayer will appear here. You may also write your own.">${esc(forms[k])}</textarea></label><div class="actions"><button type="button" data-guide-copy="${k}">Copy this prayer</button><button type="button" data-guide-action="prayers" data-guide-target="${k}">Ask AI again for this prayer only</button><button type="button" data-local-form="${k}">Use a simple starting prayer (no AI)</button></div></section>`).join('')}</div><p class="meta">The extended prayer is new wording in an older devotional style. It is not a quotation from a historical author.</p><p class="meta" id="prayer-origin">${esc(forms.origin)}${forms.at?' - '+esc(forms.at):''}</p></section>
<section class="writing-paper record-paper" id="guide-save" data-toc-label="Save my prayers"><h2>Keep these prayers</h2><p class="meta">Saving keeps your words in this browser only. After you save, a new tab opens with a copy you can download.</p><div class="actions">${u.btn('save','Save my prayers','primary')}${u.btn('download-html','Download as HTML')}${u.btn('download-text','Download as text')}${u.btn('browse','Browse saved prayers','quiet')}</div><div class="field-pair"><label class="field">Record type<select data-field="entryType">${u.options({request:'Request',thanksgiving:'Thanksgiving',mixed:'Mixed'},d.entryType)}</select></label>${u.input('topic','Title (optional)',d.topic)}</div><details><summary>Dates, tags and follow-up</summary>${u.input('prayedAt','Prayer date and time (SGT)',u.localInput(d.prayedAt),'datetime-local')}${u.input('tags','Hashtags',d.tags.map(t=>'#'+t).join(' '))}<label class="field">Request status<select data-field="answerStatus">${u.options(u.statuses,d.answerStatus)}</select></label>${u.field('answerNote','What happened (optional)',d.answerNote)}${u.input('revisit','Revisit on (no automatic reminder)',d.revisit,'date')}</details><p class="meta">No cloud journal is created. JSON backups include private details; keep them safe.</p></section></div>`;
}
function feedbackHTML(d,k){const m=d.prayerForms?.details?.[k];return m?'<strong>'+esc(m.origin||'Prayer draft')+'</strong><p>'+esc(m.message||'Read these words before you pray or share them.')+'</p>':'<p>Your prayer will appear here. You can edit it.</p>';}
function status(message,kind='status',save=false){
 const box=document.getElementById('prayer-flow-status');if(!box)return;
 box.hidden=!message;box.dataset.kind=kind;box.replaceChildren();const h=document.createElement('strong');h.textContent=kind==='error'?'Something needs attention':'Your prayers';const p=document.createElement('p');p.textContent=message;box.append(h,p);
 if(save){const b=document.createElement('button');b.type='button';b.dataset.locate='#guide-save';b.textContent='Go to Save';box.append(b);}
}
function fieldFeedback(k,heading,message,offer=false){
 const box=document.querySelector('[data-form-feedback="'+k+'"]');if(!box)return;box.replaceChildren();
 const h=document.createElement('strong');h.textContent=heading;const p=document.createElement('p');p.textContent=message;box.append(h,p);
 if(offer){const b=document.createElement('button');b.type='button';b.dataset.useReturned=k;b.textContent='See the AI version';box.append(b);}
}
function writeForms(d,values,origin,report={},baseline=null){
 d.prayerForms=G.forms(d.prayerForms);const pending=candidates.get(d)||{};
 for(const k of P.KINDS){
  if(!Object.hasOwn(values,k)){
   if(report[k])fieldFeedback(k,label[k]+' needs attention',report[k].message+(d.prayerForms[k]?' Your earlier wording is still here.':''));
   continue;
  }
  if(baseline&&d.prayerForms[k]!==baseline[k]){pending[k]=values[k];fieldFeedback(k,'Your edits have been kept','The AI wrote a new version, but you edited this prayer while it was being prepared. Your words have not been replaced.',true);continue;}
  const value=values[k];d.prayerForms[k]=value;
  const st=report[k]||{state:'local',message:'Local starting prayer - not an AI response. Edit it to express only what you can honestly pray.'};
  d.prayerForms.details[k]={origin,state:st.state,message:st.message};
  const box=document.querySelector('[data-prayer-form="'+k+'"]');if(box){const start=box.selectionStart,end=box.selectionEnd,scroll=box.scrollTop;box.value=value;if(document.activeElement===box){box.setSelectionRange(Math.min(start,value.length),Math.min(end,value.length));box.scrollTop=scroll;}}
  fieldFeedback(k,origin,st.message);delete pending[k];
 }
 candidates.set(d,pending);d.prayerForms.origin='Each prayer says where it came from.';d.prayerForms.at=new Date().toISOString();
 d.prayer=d.prayerForms.whems||d.prayerForms.extended||d.prayerForms.sentence;
 const originBox=document.getElementById('prayer-origin');if(originBox)originBox.textContent=d.prayerForms.origin;
 host.dirty();
}
function patchGuidance(d){
 if(!document.querySelector('[data-editor="pray"]')||!lastUI)return;
 const template=document.createElement('template');template.innerHTML=render(d,lastUI);
 const source=template.content;
 for(const selector of ['#guide-understanding-slot','#guide-options',...G.keys.flatMap(k=>['[data-context-focus="'+k+'"]','#question-'+k,'[data-context-followup="'+k+'"]','[data-context-references="'+k+'"]','#reply-label-'+k])]){
  const old=document.querySelector(selector),fresh=source.querySelector(selector);if(old&&fresh)old.replaceChildren(...Array.from(fresh.childNodes));
 }
 for(const k of G.keys){const box=document.querySelector('[data-guide-reply="'+k+'"]');if(box)box.placeholder=d.journey.result.areas.find(a=>a.key===k).question;}
 const start=document.getElementById('guide-reflect-start');if(start)start.textContent='Update the AI questions from my replies';
 UX.refresh();
}
function errorPanel(err,origin,action,target){
 const message=err.name==='AbortError'?'The request was cancelled. Your words are unchanged.':err.message||'The service could not complete this request. Your words are unchanged.';
 if(action==='prayers'){
  status(message+(err.code?' Reference: '+err.code+'.':'')+(err.supportId?' Support ID: '+err.supportId+'.':''),'error');
  for(const k of (target==='all'?P.KINDS:[target]))fieldFeedback(k,'Not replaced',message+' You can keep writing here. A simple starting prayer is offered below; it is not an AI answer.');
 }else{
  let box=document.getElementById('guidance-service-status');if(!box){box=document.createElement('div');box.id='guidance-service-status';box.className='prayer-flow-status';origin.closest('.actions')?.after(box);}
  box.setAttribute('role','alert');box.replaceChildren();const h=document.createElement('strong');h.textContent='AI help needs attention';const t=document.createElement('p');t.textContent=message+(err.code?' Reference: '+err.code+'.':'')+(err.supportId?' Support ID: '+err.supportId+'.':'');box.append(h,t);
 }
 if(action!=='prayers')host.notify(message,'','error');
}
function init(h){host=h;
 document.addEventListener('input',e=>{const el=e.target,d=host.draft();if(!d||!el.closest('[data-editor="pray"]'))return;const g=d.journey=G.state(d.journey);
  if(el.dataset.journey){g[el.dataset.journey]=el.value;if(['issue','context','summary'].includes(el.dataset.journey)){g.summaryConfirmed=false;const c=document.querySelector('[data-journey-confirm]');if(c)c.checked=false;}host.dirty();}
  if(el.dataset.guideReply){g.replies[el.dataset.guideReply]=el.value;host.dirty();}
  if(el.dataset.prayerForm){d.prayerForms=G.forms(d.prayerForms);const k=el.dataset.prayerForm;d.prayerForms[k]=el.value;d.prayerForms.details[k]={origin:'Your edited prayer',state:'edited',message:'Your wording is kept. AI will not overwrite it while you are editing.'};d.prayer=d.prayerForms.whems||d.prayerForms.extended||d.prayerForms.sentence;host.dirty();}
 });
 document.addEventListener('change',e=>{const d=host.draft(),el=e.target;if(!d)return;
  if(el.hasAttribute('data-guidance-consent')){consents.pray=el.checked;if(!el.checked)controller?.abort();const state=document.getElementById('ai-state');if(state)state.textContent=aiState();}
  if(el.hasAttribute('data-journey-confirm')){d.journey=G.state(d.journey);d.journey.summaryConfirmed=el.checked;host.dirty();}
  if(el.hasAttribute('data-guide-voice')){d.journey=G.state(d.journey);d.journey.voice=el.value;host.dirty();}
 });
 document.addEventListener('click',async e=>{
  const jump=e.target.closest('[data-guide-jump]');if(jump){e.preventDefault();UX.reveal('#reflection-'+jump.dataset.guideJump);return;}
  const copy=e.target.closest('[data-guide-copy]');if(copy){const f=G.forms(host.draft()?.prayerForms);try{await navigator.clipboard.writeText(f[copy.dataset.guideCopy]);host.notify('Prayer copied.');}catch{document.querySelector('[data-prayer-form="'+copy.dataset.guideCopy+'"]')?.select();host.notify('Use your device’s Copy command on the selected prayer.');}return;}
  const b=e.target.closest('[data-guide-action],[data-quick-pray],[data-local-form],[data-use-returned]');if(!b)return;
  // The quick button moves the page under the finger. Within 900ms, a second tap on it or on any control in the prayers section it revealed is the same tap, not a new request.
  if(quickAt&&performance.now()-quickAt<900&&(b.hasAttribute('data-quick-pray')||b.closest('#guide-prayers')))return;
  if(b.hasAttribute('data-local-form')){const d=host.draft(),k=b.dataset.localForm;if(!P.KINDS.includes(k))return;if(d.prayerForms?.[k]&&!confirm('Replace only this prayer with a simple starting prayer? The other prayers will be kept.'))return;const f=G.local(d);writeForms(d,{[k]:f[k]},'Local starting prayer - no AI');return;}
  if(b.hasAttribute('data-use-returned')){const d=host.draft(),k=b.dataset.useReturned,value=candidates.get(d)?.[k];if(!value)return;host.panel('The AI version','<p>Your edited prayer has not been replaced. Copy any wording you wish to use, or close this panel to keep your own words.</p><p class="pre">'+esc(value)+'</p>');return;}
  const quick=b.hasAttribute('data-quick-pray');if(quick)quickAt=performance.now();
  const action=quick?'local':b.dataset.guideAction,target=P.KINDS.includes(b.dataset.guideTarget)?b.dataset.guideTarget:'all';
  if(action==='historic')return host.panel('Classic prayers',readings());if(action==='cancel'){controller?.abort();return;}
  const d=host.draft();if(!d)return;d.journey=G.state(d.journey);if(busy)return host.notify('One AI request is already running. Please wait or cancel it.');
  const missing=[];
  if(!d.journey.issue.trim())missing.push({selector:'#guidance-issue',label:'Write a few words first',message:'Write what is happening and what you are trying to decide.',suggestion:'I am considering …; what I know is …; what I still need to understand is …',check:'text'});
  if(action!=='local'&&!consents.pray)missing.push({selector:'#guidance-consent',label:'AI help needs your permission',message:"To use AI, tick the consent box under 'Ask AI to help'. You do not need AI to pray. Tap 'Pray with what I have written' instead.",check:'checked'});
  if(action==='prayers'&&d.journey.result){
   if(!d.journey.summary.trim())missing.push({selector:'#guidance-summary',label:'Check the AI summary',message:'Write or correct the summary so the prayers say what you actually mean.',suggestion:'I am seeking wisdom about: '+d.journey.issue,check:'text'});
   if(!d.journey.summaryConfirmed)missing.push({selector:'#guidance-confirm',label:'Confirm the summary',message:'Please correct and confirm the AI summary before the prayers are written. Only you can say that it is accurate.',check:'checked'});
  }
  if(UX.requireActions(missing,b,action==='reflect'?'the AI questions':'making your prayers'))return;
  if(action==='reflect'&&d.journey.turns.length>=12){host.notify('This entry has had 12 rounds of AI help. Save it and add a follow-up to keep its history.');UX.reveal('#guide-save');return;}
  const kinds=target==='all'?P.KINDS:[target];
  if(['local','prayers'].includes(action)&&kinds.some(k=>d.prayerForms?.[k]?.trim())&&!confirm('Replace '+(target==='all'?'these three prayers':'this prayer')+'? Any edits you make while the new words are prepared will be kept. Saved entries are unchanged.'))return;
  if(action==='local'){const f=G.local(d);writeForms(d,f,'Local starting prayer - no AI');status('Your three prayers are ready below. Nothing was sent. Read them and change any words you wish.','status',true);if(quick)UX.reveal('#guide-prayers h2');return;}
  const data=G.payload(d,action);data.target=target;const snapshot=JSON.stringify(data),baseline=G.forms(d.prayerForms);
  busy=true;controller=new AbortController();document.getElementById('guidance-service-status')?.remove();
  if(action==='prayers'){host.notify('');status('Preparing '+(target==='all'?'all three prayers':label[target])+'. They will fill in place. Your issue, replies and scroll position are kept.');for(const k of kinds)fieldFeedback(k,'Preparing with AI','You can keep writing. Any edits you make here will be kept.');}
  else host.notify('Asking AI about your issue and replies…');
  document.querySelectorAll('[data-guide-action="reflect"],[data-guide-action="prayers"],[data-guide-action="local"],[data-local-form],[data-quick-pray]').forEach(x=>x.disabled=true);document.querySelectorAll('[data-guide-action="cancel"]').forEach(x=>x.dataset.busy='true');
  try{
   const response=await fetch('/api/guidance',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',referrerPolicy:'no-referrer',signal:controller.signal,body:JSON.stringify(data)});
   let result;try{result=await response.json();}catch{throw Object.assign(Error('The website received an unreadable response. Your previous wording is kept.'),{code:'WEBSITE_RESPONSE'});}
   if(!response.ok)throw Object.assign(Error(result.error||'The service could not complete the request.'),{code:result.code,supportId:result.supportId});
   const now=G.payload(d,action);now.target=target;
   if(host.draft()!==d||JSON.stringify(now)!==snapshot)throw Object.assign(Error('The issue or replies changed during preparation. The earlier response was not applied. Send your current wording again.'),{code:'CONTEXT_CHANGED'});
   if(action==='reflect'){
    const r=G.validateGuide(result.result),g=d.journey;g.turns=[...g.turns,{at:result.at,summary:r.summary,replies:{...g.replies},questions:{...data.questions}}];g.result=r;g.summary=r.summary;g.summaryConfirmed=false;g.model=result.model;g.generatedAt=result.at;host.dirty();patchGuidance(d);UX.reveal('#guide-understanding');host.notify('Check the AI summary. The questions have changed around your issue; your own answers and prayer edits are kept.');
   }else{
    const report=P.inspect(result.result,target);
    // Local re-validation never trusts provider status flags without inspecting the actual text.
    writeForms(d,report.values,'AI-assisted draft - review before use',report.statuses,baseline);
    const count=Object.values(report.statuses).filter(s=>s.state==='ready').length;
    status(report.complete?'The requested prayers have filled in place. Review each one; any edits made during preparation are kept.':count+' of '+kinds.length+' requested forms are ready to review. Each unfinished form explains what is missing and offers a simple starting prayer or an AI retry.');
   }
  }catch(err){errorPanel(err,b,action,target);}finally{busy=false;controller=null;document.querySelectorAll('[data-guide-action],[data-local-form],[data-quick-pray]').forEach(x=>{x.disabled=false;delete x.dataset.busy;});}
 });
}
function readings(){return `<p>These are companions to Scripture, not authorities alongside it. Read the source, then express your own prayer. Historical authors differ in theology; inclusion is not endorsement of everything they wrote.</p><section><h3>Early Church · Augustine</h3><p><em>Confessions</em>, Book I opens in praise and in the desire to seek and know God. Notice how understanding and affection are brought together.</p><a href="https://www.newadvent.org/fathers/110101.htm" target="_blank" rel="noopener noreferrer" data-external>Read Book I in translation</a></section><section><h3>Medieval · Anselm</h3><p>The opening of <em>Proslogion</em> turns reflection into prayerful seeking. Consider how the desire to understand can remain humble before God.</p><a href="https://sourcebooks.fordham.edu/basis/anselm-proslogium.asp" target="_blank" rel="noopener noreferrer" data-external>Read the translated source</a></section><section><h3>Puritan tradition · Matthew Henry</h3><p><em>A Method for Prayer</em> organises biblical expressions under adoration, confession, petition, thanksgiving, intercession and conclusion. The linked edition has modern editorial revision.</p><a href="https://www.matthewhenry.org/read/" target="_blank" rel="noopener noreferrer" data-external>Read A Method for Prayer</a></section><section><h3>Modern collection · The Valley of Vision</h3><p>Arthur Bennett’s collection draws on Puritan devotion. It is not an ancient text. Wholehearted’s extended prayers are original drafts, not excerpts from this book.</p><a href="https://banneroftruth.org/us/store/theauthor/bennett-arthur/" target="_blank" rel="noopener noreferrer" data-external>Publisher’s source</a></section>`;}
root.WholeheartedJourneyUI={render,init,readings};})(globalThis);
