/* The open W.H.E.M.S. workspace. Only explicit AI buttons send the current issue. */
(function(root){'use strict';const G=root.WholeheartedGuidance,C=root.WholeheartedCore,UX=root.WholeheartedExperience;
let host=null,busy=false,controller=null;const consents={pray:false,journal:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={sentence:'One-sentence prayer',whems:'W.H.E.M.S. prayer',extended:'Extended prayer - reverent and Christ-centred'};
const starters={W:['What action are you considering, and what would it seek to accomplish?','What would make it difficult to change your preferred response?'],H:['What good are you hoping for, and for whom?','What motives do you recognise? Do not assume that every desire is wrong.'],E:['What are you feeling, and what have other people actually expressed?','How might your feelings affect your response without deciding what is true?'],M:['What do you know, and what are you presently assuming?','What context, Scripture or wise counsel could change your understanding?'],S:['How does your relationship with Christ bear on this matter?','What responsibility is yours, and what outcome must you entrust to God?']};
const care={
W:['Where has God helped you become willing?','Where do you need help to act faithfully?'],
H:['What love or concern can you give thanks for?','What desires would you bring before God?'],
E:['What comfort or patience have you received?','What feeling or response needs help?'],
M:['What has become clearer?','Where do you still need wisdom?'],
S:['What grace or hope can you give thanks for?','What do you need to entrust to God?']};
function render(d,u){const g=G.state(d.journey),forms=G.forms(d.prayerForms),r=g.result;
return `<div data-editor="pray" class="guided-workspace"><div class="page-heading"><div><p class="meta">Describe · understand · pray · respond</p><h1 tabindex="-1">Bring the whole matter before God.</h1><p>Gratitude and struggle can belong in the same prayer. Begin in ordinary words; the five invitations below are already open.</p></div>${u.btn('browse','Browse journal')}</div>
<section class="writing-paper issue-paper" id="guide-issue" data-toc-label="Your issue"><h2>What is happening, and what are you trying to decide?</h2><label class="field">Your issue<textarea id="guidance-issue" data-journey="issue" rows="4" maxlength="4000" placeholder="For example: should I speak with my daughter or pray for her as she faces a steep learning curve in her research year?">${esc(g.issue)}</textarea></label><label class="field">Context or correction · optional<textarea data-journey="context" maxlength="4000" rows="3" placeholder="What has actually been said? What is uncertain? Leave out identifying details you do not need to share.">${esc(g.context)}</textarea></label>
<div class="consent-box" id="guide-consent" data-toc-label="Choose AI guidance"><h3>Let’s consider this together</h3><p>Optional contextual guidance. Describe the concern, then let the questions help you explore it. You remain free to correct the guidance and choose your response.</p><p>AI guidance sends this issue, context and selected replies to OpenAI through this website. It does not send your journal, hidden notes or earlier entries. It is not therapy or a message from God.</p><p class="meta">The app does not store requests on its server and requests no API response storage. OpenAI may retain data under its service policies; this is not a promise of zero retention.</p><label class="check"><input id="guidance-consent" type="checkbox" data-guidance-consent ${consents.pray?'checked':''}><span>I agree to send the current issue and replies for AI guidance.</span></label><div class="actions"><button type="button" id="guide-reflect-start" data-guide-action="reflect" class="primary">${r?'Update guidance from my replies':'Guide me through this'}</button><button type="button" data-guide-action="cancel">Cancel AI request</button></div><p class="meta">Without consent, nothing is sent. You can use the open questions and local prayer drafts instead.</p></div></section>
${r?`<section class="callout interpretation" id="guide-understanding" data-toc-label="Review your understanding"><h2>Is this a fair understanding?</h2><p class="meta">AI-proposed summary · ${esc(g.model)}. Correct it before relying on it.</p><label class="field">Your understanding<textarea id="guidance-summary" rows="3" data-journey="summary" maxlength="2500">${esc(g.summary)}</textarea></label><label class="check"><input id="guidance-confirm" type="checkbox" data-journey-confirm ${g.summaryConfirmed?'checked':''}><span>This describes my concern, with any corrections above.</span></label><div class="facts-grid"><div><h3>Reported in your words</h3>${r.statedFacts.map(t=>'<p>'+esc(t)+'</p>').join('')||'<p>No additional facts recorded.</p>'}</div><div><h3>Still to understand</h3>${r.uncertainties.map(t=>'<p>'+esc(t)+'</p>').join('')||'<p>No additional uncertainty recorded by the guide; check this yourself.</p>'}</div></div>${r.clarification?'<p><strong>Begin here:</strong> '+esc(r.clarification)+'</p>':''}${r.safetyNote?'<p class="safety-note">'+esc(r.safetyNote)+'</p>':''}</section>`:''}
<nav class="whems-jumps" aria-label="Jump to an open reflection">${C.AREAS.map(a=>`<a href="#reflection-${a.key}" data-guide-jump="${a.key}">${a.key} · ${a.name}</a>`).join('')}</nav>
<section class="open-whems" aria-label="Five open W.H.E.M.S. reflections">${C.AREAS.map(a=>{const q=r?.areas.find(x=>x.key===a.key),v=d.areas[a.key];return `<section class="area open-area" id="reflection-${a.key}" data-toc-label="${a.key} · ${a.name}" data-area="${a.key}"><h2><span class="area-mark">${a.key}</span>${a.name}</h2><p>${esc(a.help)}</p>${q?'<p class="guidance-source">Questions shaped around your issue</p><p class="context-focus"><strong>What we’re considering:</strong> '+esc(q.focus)+'</p>':''}<h3 id="question-${a.key}" class="reply-question">${esc(q?.question||starters[a.key][0])}</h3><p>${esc(q?.followup||starters[a.key][1])}</p><label class="field reply-field"><span id="reply-label-${a.key}">${q?"Your response to this question":"My reflection"} · ${a.name}</span><textarea aria-labelledby="question-${a.key} reply-label-${a.key}" data-guide-reply="${a.key}" rows="3" maxlength="2000" placeholder="${esc(q?.question||starters[a.key][0])}">${esc(g.replies[a.key])}</textarea><span class="reply-support">Take your time. Start with what you know, and say what remains uncertain.</span></label>${a.key==='S'?`<p>Belonging is not a score. A struggle does not by itself determine salvation.</p><label class="field">How should prayer express belonging?<select data-field="belonging">${u.options({'':'Do not assume my faith',trusting:'I am trusting Christ',exploring:'I am exploring faith in Christ',private:'Leave this personal'},d.belonging)}</select></label>`:''}<div class="reflection-columns">${['thank','ask'].map(t=>`<div><label class="check reflection-choice"><input type="checkbox" data-field="areas.${a.key}.${t}" ${v[t]?'checked':''}><span><strong>${t==='thank'?'Include my thanksgiving':'Include my request'}</strong><small>${esc(care[a.key][t==='thank'?0:1])}</small></span></label><div class="area-note" data-note="${a.key}-${t}" ${v[t]?'':'hidden'}>${u.field('areas.'+a.key+'.'+t+'Note',t==='thank'?'Father, thank you for…':'Father, please help me…',v[t+'Note'],(q?'In this situation, ':'')+(t==='thank'?'I can thank you for…':'please help me with…'),3)}</div></div>`).join('')}</div><div class="reading-links">${(q?.referenceIds.length?q.referenceIds:[u.byReference(a.passage).id]).map(u.ref).join('')}</div></section>`;}).join('')}</section>
<div class="actions"><button type="button" id="guide-reflect-followup" data-guide-action="reflect" class="secondary">Reflect on these replies with me</button></div>
<section class="writing-paper decision-paper" id="guide-decision" data-toc-label="Discernment and next step"><h2>Discernment and the next faithful step</h2><p>These are considerations, not a divine verdict. You can remain uncertain and still pray.</p>${r?.options.map(o=>`<article class="decision-option"><h3>${esc(o.action)}</h3><p><strong>Reason to consider:</strong> ${esc(o.reason)}</p><p><strong>Be careful about:</strong> ${esc(o.caution)}</p><div class="reading-links">${o.referenceIds.map(u.ref).join('')}</div></article>`).join('')||'<p>Consider what Scripture makes clear, what information is missing, whose interests are affected, and whether wise counsel is needed.</p>'}${u.field('advice','My discernment notes',d.advice,'What seems wise? What remains uncertain?')}${u.field('nextStep','The next step I choose',d.nextStep,'For example: ask whether a listening conversation would help, rather than assuming advice is wanted.')}<details><summary>Scripture and the Spirit’s fruit</summary>${u.field('scripture','Passage and what it teaches',d.scripture)}<div class="attached-refs">${d.referenceIds.map(u.ref).join('')}</div>${u.btn('scripture','Read the Scripture index')}<div class="fruits">${C.FRUIT.map(f=>`<label class="check"><input type="checkbox" data-fruit="${f}" ${d.fruit.includes(f)?'checked':''}><span>${f}</span></label>`).join('')}</div>${u.ref('galatians-5-22-25')}</details></section>
<section class="writing-paper final-prayers" id="guide-prayers" data-toc-label="Three prayer forms"><h2>Three ways to bring this before God</h2><p>The same concern in three forms. Greater length does not make a prayer more powerful.</p><label class="field">Praying as<select data-guide-voice><option value="personal" ${g.voice==='personal'?'selected':''}>Personally · I / my</option><option value="community" ${g.voice==='community'?'selected':''}>Family or congregation · we / our</option></select></label><p class="meta">For shared prayer, remove private identifying details from the issue and replies before generating or sharing. Review every form before using it aloud.</p><div class="actions"><button type="button" id="guide-prayers-ai" data-guide-action="prayers" class="primary">Create all three with AI</button><button type="button" data-guide-action="local">Create all three without sending</button><button type="button" data-guide-action="historic" class="quiet">Read before praying</button></div><p class="meta">The extended prayer is original, Puritan-influenced devotional wording - not a quotation from a historical author.</p><div id="three-prayer-forms">${Object.entries(label).map(([k,l])=>`<section class="prayer-form-block" id="prayer-${k}" data-toc-label="${l}" data-prayer-kind="${k}"><h3>${l}</h3><label class="field">Edit ${k==='sentence'?'the sentence':k==='whems'?'the W.H.E.M.S. prayer':'the extended prayer'}<textarea data-prayer-form="${k}" rows="${k==='sentence'?3:k==='whems'?12:18}" maxlength="24000" placeholder="Your ${l.toLowerCase()} will appear here. You may also write your own.">${esc(forms[k])}</textarea></label><button type="button" data-guide-copy="${k}">Copy this prayer</button></section>`).join('')}</div>${forms.origin?'<p class="meta">'+esc(forms.origin)+' · '+esc(forms.at)+'</p>':''}</section>
<section class="writing-paper record-paper" id="guide-save" data-toc-label="Save and record details"><h2>Keep this prayer journey</h2><div class="field-pair"><label class="field">Record type<select data-field="entryType">${u.options({request:'Request',thanksgiving:'Thanksgiving',mixed:'Mixed'},d.entryType)}</select></label>${u.input('topic','Title · optional',d.topic)}</div><details><summary>Dates, tags and follow-up</summary>${u.input('prayedAt','Prayer date and time · SGT',u.localInput(d.prayedAt),'datetime-local')}${u.input('tags','Hashtags',d.tags.map(t=>'#'+t).join(' '))}<label class="field">Request status<select data-field="answerStatus">${u.options(u.statuses,d.answerStatus)}</select></label>${u.field('answerNote','Response / outcome notes',d.answerNote)}${u.input('revisit','Revisit on · no automatic reminder',d.revisit,'date')}</details><div class="actions">${u.btn('save','Save all three & open download','primary')}${u.btn('download-html','Download all three as HTML')}${u.btn('download-text','Download text')}</div><p class="meta">Saving keeps the issue, reflections, discernment and all three forms together in this browser. No cloud journal is created. JSON backups include private details; keep them secure.</p></section></div>`;
}
function init(h){host=h;document.addEventListener('input',e=>{const el=e.target,d=host.draft();if(!d||!el.closest('[data-editor="pray"]'))return;const g=d.journey=G.state(d.journey);if(el.dataset.journey){g[el.dataset.journey]=el.value;if(['issue','context','summary'].includes(el.dataset.journey)){g.summaryConfirmed=false;const c=document.querySelector('[data-journey-confirm]');if(c)c.checked=false;}host.dirty();}if(el.dataset.guideReply){g.replies[el.dataset.guideReply]=el.value;host.dirty();}if(el.dataset.prayerForm){d.prayerForms=G.forms(d.prayerForms);d.prayerForms[el.dataset.prayerForm]=el.value;d.prayer=d.prayerForms.whems||d.prayerForms.extended||d.prayerForms.sentence;host.dirty();}});
document.addEventListener('change',e=>{const d=host.draft(),el=e.target;if(!d)return;if(el.hasAttribute('data-guidance-consent')){consents.pray=el.checked;if(!el.checked)controller?.abort();}if(el.hasAttribute('data-journey-confirm')){d.journey=G.state(d.journey);d.journey.summaryConfirmed=el.checked;host.dirty();}if(el.hasAttribute('data-guide-voice')){d.journey=G.state(d.journey);d.journey.voice=el.value;host.dirty();}});
document.addEventListener('click',async e=>{const jump=e.target.closest('[data-guide-jump]');if(jump){e.preventDefault();UX.reveal('#reflection-'+jump.dataset.guideJump);return;}const copy=e.target.closest('[data-guide-copy]');if(copy){const f=G.forms(host.draft()?.prayerForms);try{await navigator.clipboard.writeText(f[copy.dataset.guideCopy]);host.notify('Prayer copied.');}catch{document.querySelector(`[data-prayer-form="${copy.dataset.guideCopy}"]`)?.select();host.notify('Use your device’s Copy command on the selected prayer.');}return;}const b=e.target.closest('[data-guide-action]');if(!b)return;const action=b.dataset.guideAction;if(action==='historic')return host.panel('Read before praying',readings());if(action==='cancel'){controller?.abort();return;}
const d=host.draft();if(!d)return;d.journey=G.state(d.journey);
if(busy)return host.notify('One guidance request is already running. Please wait or cancel it.');
const missing=[];
if(!d.journey.issue.trim())missing.push({selector:'#guidance-issue',label:'Describe your issue',message:'Tell us what is happening and what you are trying to decide.',check:'text'});
if(action!=='local'&&!consents.pray)missing.push({selector:'#guidance-consent',label:'Choose whether to use AI guidance',message:'Please read the consent statement and tick it only if you agree. You can use the local prayer drafts without sending your words.',check:'checked'});
if(action==='prayers'&&d.journey.result){
 if(!d.journey.summary.trim())missing.push({selector:'#guidance-summary',label:'Review the proposed understanding',message:'Write or correct the understanding so the prayers are based on your actual concern.',check:'text'});
 if(!d.journey.summaryConfirmed)missing.push({selector:'#guidance-confirm',label:'Confirm your understanding',message:'Please correct and confirm the proposed understanding before generating the final prayers. Tick this acknowledgement yourself when it is accurate.',check:'checked'});
}
if(UX.requireActions(missing,b,action==='reflect'?'contextual guidance':'preparing your prayers'))return;
if(action==='reflect'&&d.journey.turns.length>=12){host.notify('This entry has 12 guidance rounds. Save it and create a linked follow-up to preserve its history.');UX.reveal('#guide-save');return;}
if(['local','prayers'].includes(action)&&Object.values(G.forms(d.prayerForms)).slice(0,3).some(s=>s.trim())&&!confirm('Replace the three prayer drafts? Copy or save personal edits first. Saved journal entries will not be overwritten.'))return;
if(action==='local'){d.prayerForms=G.local(d);d.prayer=d.prayerForms.whems;host.dirty();host.render();UX.reveal('#guide-prayers');return host.notify('Three local structured drafts are ready. No words were sent to AI. Review and edit each before praying.');}
const data=G.payload(d,action),snapshot=JSON.stringify(data);busy=true;controller=new AbortController();host.notify(action==='reflect'?'Considering your issue and replies…':'Preparing all three prayers…');document.querySelectorAll('[data-guide-action="reflect"],[data-guide-action="prayers"]').forEach(x=>x.disabled=true);document.querySelectorAll('[data-guide-action="cancel"]').forEach(x=>x.dataset.busy='true');
try{const response=await fetch('/api/guidance',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',referrerPolicy:'no-referrer',signal:controller.signal,body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Guidance was unavailable.');if(host.draft()!==d||JSON.stringify(G.payload(d,action))!==snapshot)throw Error('Your issue changed while guidance was running. The earlier response was not applied. Submit your current wording.');
if(action==='reflect'){const r=G.validateGuide(result.result);const g=d.journey;g.turns=[...g.turns,{at:result.at,summary:r.summary,replies:{...g.replies},questions:{...data.questions}}];g.result=r;g.summary=r.summary;g.summaryConfirmed=false;g.model=result.model;g.generatedAt=result.at;}else{d.prayerForms=G.validatePrayers(result.result);d.prayer=d.prayerForms.whems;}
host.dirty();host.render();UX.reveal(action==='reflect'?'#guide-understanding':'#guide-prayers');host.notify(action==='reflect'?'Read and correct the proposed understanding. Each open W.H.E.M.S. area now has contextual questions.':'All three prayer drafts are ready. Review their wording and facts before praying or sharing.');
}catch(err){host.notify(err.name==='AbortError'?'Request cancelled. Your earlier writing remains.':err.message||'The request failed; your writing remains.');}finally{busy=false;controller=null;document.querySelectorAll('[data-guide-action]').forEach(x=>{x.disabled=false;delete x.dataset.busy;});}});
}
function readings(){return `<p>These are companions to Scripture, not authorities alongside it. Read the source, then express your own prayer. Historical authors differ in theology; inclusion is not endorsement of everything they wrote.</p><section><h3>Early Church · Augustine</h3><p><em>Confessions</em>, Book I opens in praise and in the desire to seek and know God. Notice how understanding and affection are brought together.</p><a href="https://www.newadvent.org/fathers/110101.htm" target="_blank" rel="noopener noreferrer" data-external>Read Book I in translation</a></section><section><h3>Medieval · Anselm</h3><p>The opening of <em>Proslogion</em> turns reflection into prayerful seeking. Consider how the desire to understand can remain humble before God.</p><a href="https://sourcebooks.fordham.edu/basis/anselm-proslogium.asp" target="_blank" rel="noopener noreferrer" data-external>Read the translated source</a></section><section><h3>Puritan tradition · Matthew Henry</h3><p><em>A Method for Prayer</em> organises biblical expressions under adoration, confession, petition, thanksgiving, intercession and conclusion. The linked edition has modern editorial revision.</p><a href="https://www.matthewhenry.org/read/" target="_blank" rel="noopener noreferrer" data-external>Read A Method for Prayer</a></section><section><h3>Modern collection · The Valley of Vision</h3><p>Arthur Bennett’s collection draws on Puritan devotion. It is not an ancient text. Wholehearted’s extended prayers are original drafts, not excerpts from this book.</p><a href="https://banneroftruth.org/us/store/theauthor/bennett-arthur/" target="_blank" rel="noopener noreferrer" data-external>Publisher’s source</a></section>`;}
root.WholeheartedJourneyUI={render,init,readings};})(globalThis);
