'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../core.js'),J=require('../journal.js'),X=require('../export.js'),T=require('../theme.js'),A=require('../about.js');
function fixture(){const d=J.blank('mixed','2026-09-19T17:00:00Z','safe-12345678');d.topic='Private matter';d.prayer='Father, these are edited words.\nAmen.';d.tags=['work'];d.form='personal';d.areas.E.thank=true;d.areas.E.thankNote='pause';d.areas.E.ask=true;d.areas.E.askNote='gentleness';d.answerStatus='waiting';d.answerNote='Not clear';d.advice='Speak with a trusted friend.';return d;}
test('Download is a complete script-free, self-contained HTML file',()=>{const h=X.html(fixture());assert.match(h,/^<!doctype html>/);assert.match(h,/<meta charset="utf-8">/);assert.match(h,/name="viewport"/);assert.match(h,/<\/html>$/);assert.doesNotMatch(h,/<script\b|<link\b|<iframe\b|<form\b/i);});
test('App and HTML download use the same design tokens',()=>{const h=X.html(fixture());assert.ok(h.includes(T.css));assert.ok(fs.readFileSync(path.join(__dirname,'../public/styles.css'),'utf8').startsWith(T.css));});
test('HTML includes edited prayer and all requested record fields',()=>{const d=fixture(),h=X.html(d,{version:'0.0.002',sourceCommit:'a'.repeat(40)});for(const s of [d.prayer,'Mixed','pause','gentleness',d.answerNote,d.advice,'#work','0.0.002'])assert.ok(h.includes(s),s);});
test('HTML filename contains date and neutral ID, never the private matter',()=>{assert.equal(X.filename(fixture()),'Wholehearted-Prayer-2026-09-20-12345678.html');});
test('Deselected private notes and revision history stay out of a reading copy',()=>{const d=fixture();d.areas.S.askNote='HIDDEN';d.revisions=[{at:'2026-09-20T12:00:00Z',record:{...fixture(),prayer:'HISTORY'}}];const h=X.html(d);assert.ok(!h.includes('HIDDEN'));assert.ok(!h.includes('HISTORY'));});
test('Export escapes hostile content across private fields',()=>{const d=fixture(),payload='<script>alert(1)</script><img onerror=alert(1)>';for(const k of ['topic','prayer','advice','scripture','context','nextStep','answerNote'])d[k]=payload;d.areas.E.askNote=payload;const h=X.html(d);assert.ok(!h.includes(payload));assert.match(h,/&lt;script&gt;/);});
test('Export never mutates journal state',()=>{const d=fixture(),before=JSON.stringify(d);X.html(d);X.article(d,'h2');assert.equal(JSON.stringify(d),before);});
test('Legacy core records remain exportable',()=>{const d=C.blank('thanks','2026-09-19T04:00:00Z','old');d.prayer='Original prayer';assert.ok(X.html(d).includes('Original prayer'));});
test('All original poem lines are preserved in About text',()=>{const lines=[...A.content().matchAll(/class="poem-line[^"]*">([^<]+)<\/span>/g)].map(x=>x[1]);assert.deepEqual(lines,['Inside the quiet chambers of the chest,','The Heart beats out its steady, sacred drum,','While Emotions rise like oceans, manifest,','Stirring the deep where quiet shadows come.','The Will stands firm, a beacon in the night,','Guiding the steps through storms that wildly roll,','As the sharp Mind unravels dark to light,','All held within the eternal, breathing Soul.','When these five rivers gather and collide,','The fragile banks of ordinary break;','We are whelmed beneath the brilliant, rising tide,','Alive to every truth they leave awake.']);assert.equal((A.content().match(/class="poem-line/g)||[]).length,12);});
test('Display build format is separate from valid package version',()=>{const r=require('../release.json'),p=require('../package.json');assert.equal('0.0.'+String(r.build).padStart(3,'0'),'0.0.005');assert.equal(p.version,'0.0.5');assert.ok(!fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').includes('· 2.1'));});
test('App does not auto-save or compute a godliness or answer score',()=>{const code=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');assert.equal((code.match(/localStorage\.setItem\(/g)||[]).length,1);assert.ok(!code.slice(code.indexOf('function fieldChange'),code.indexOf("document.addEventListener('input'")).includes('J.write('));assert.ok(!code.includes('answerRate'));assert.ok(code.includes('Nothing is saved automatically'));});
