'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const P=require('../prayer-output.js'),G=require('../guidance-core.js'),J=require('../journal.js'),X=require('../export.js'),T=require('../teaching.js'),handler=require('../api/guidance.js');
const words=n=>Array.from({length:n},()=> 'word').join(' ');
const prayers=()=>({sentence:'Father, help me respond with patience.',whems:{W:'Father, help me obey.',H:'Father, search my motives.',E:'Father, help me respond gently.',M:'Father, teach me wisdom.',S:'Father, help me understand grace in Christ.'},extended:words(470)});
const req=body=>({method:'POST',headers:{origin:'https://prayer.test',host:'prayer.test','content-type':'application/json','x-forwarded-for':'192.0.2.5'},body});
const res=()=>({setHeader(){},status(n){this.code=n;return this;},json(x){this.body=x;return this;}});
const input=(target='all')=>{const d=J.blank();d.journey.issue='Private fixture issue - never in logs';return {...G.payload(d,'prayers'),target};};
const envelope=x=>({status:'completed',output:[{type:'reasoning',summary:[]},{type:'message',content:[{type:'output_text',text:JSON.stringify(x)}]}]});
const fetchOriginal=global.fetch,warnOriginal=console.warn,key=process.env.openai_key,model=process.env.openai_model;const logs=[];
test.before(()=>{process.env.openai_key='PRIVATE-TEST-SECRET';process.env.openai_model='gpt-5.4-mini';console.warn=x=>logs.push(x);});
test.after(()=>{global.fetch=fetchOriginal;console.warn=warnOriginal;for(const [k,v]of [['openai_key',key],['openai_model',model]])if(v===undefined)delete process.env[k];else process.env[k]=v;});
test('Structured five-part prayer receives deterministic headings',()=>{const r=P.inspect(prayers());assert.ok(r.complete);for(const [k,n]of Object.entries(P.NAMES))assert.ok(r.values.whems.includes(k+' - '+n+'\n'));});
test('Legacy Markdown headings do not reject an otherwise complete prayer',()=>{const p=prayers();p.whems=Object.entries(P.NAMES).map(([k,n])=>'### **'+k+' - '+n+'**\nFather, help me.').join('\n\n');assert.ok(P.inspect(p).complete);});
test('Plain names are accepted as legacy headings without inventing new content',()=>{const p=prayers();p.whems=Object.values(P.NAMES).map(n=>n+':\nFather, help me.').join('\n\n');assert.ok(P.inspect(p).complete);});
test('Missing extended prayer does not discard two returned forms',()=>{const p=prayers();delete p.extended;const r=P.inspect(p);assert.equal(r.statuses.extended.state,'missing');assert.ok(r.values.sentence);assert.ok(r.values.whems);assert.ok(!r.complete);});
test('Missing Soul is identified rather than generated or treated as a user obligation',()=>{const p=prayers();delete p.whems.S;const r=P.inspect(p);assert.equal(r.statuses.whems.state,'incomplete');assert.match(r.statuses.whems.message,/Soul/);assert.doesNotMatch(r.values.whems,/S - Soul/);assert.ok(r.values.extended);});
test('A short extended prayer remains a labelled incomplete draft',()=>{const p=prayers();p.extended=words(40);const r=P.inspect(p);assert.equal(r.values.extended,p.extended);assert.equal(r.statuses.extended.code,'EXTENDED_SHORT');});
test('Invalid form types and oversized forms are refused independently',()=>{let p=prayers();p.sentence={bad:true};p.extended='a'.repeat(24001);let r=P.inspect(p);assert.ok(!('sentence' in r.values));assert.ok(!('extended'in r.values));assert.equal(r.statuses.whems.state,'ready');});
test('A targeted response does not demand or modify the other forms',()=>{const r=P.inspect({extended:words(470)},'extended');assert.ok(r.complete);assert.deepEqual(Object.keys(r.values),['extended']);});
test('Per-form origin and incomplete state survive saving and HTML export',()=>{const d=J.blank();d.prayerForms=G.forms({...P.inspect(prayers()).values,details:{extended:{origin:'Local starting prayer - no AI',state:'local',message:'Local fallback, reviewed by writer.'}}});d.prayer=d.prayerForms.whems;const restored=J.decode(JSON.stringify({version:3,entries:J.upsert([],d)}))[0];assert.equal(restored.prayerForms.details.extended.state,'local');assert.match(X.html(restored),/Local fallback, reviewed by writer/);});
test('Targeted API call asks only for the requested form, with no model fallback',async()=>{handler._reset();let body;global.fetch=async(u,o)=>{body=JSON.parse(o.body);return {ok:true,json:async()=>envelope({extended:words(470)})};};const r=res();await handler(req(input('extended')),r);assert.equal(r.code,200);assert.deepEqual(body.text.format.schema.required,['extended']);assert.equal(body.model,'gpt-5.4-mini');assert.equal(body.store,false);assert.deepEqual(Object.keys(r.body.result),['extended']);});
test('All-form API uses a schema with five named prayer fields, not prose heading guesses',()=>{const w=handler._prayersSchema.properties.whems;assert.deepEqual(w.required,G.keys);assert.equal(w.additionalProperties,false);});
test('Partial API response reports the missing form and retains the other two',async()=>{handler._reset();const p=prayers();delete p.extended;global.fetch=async()=>({ok:true,json:async()=>envelope(p)});const r=res();await handler(req(input()),r);assert.equal(r.code,200);assert.equal(r.body.complete,false);assert.equal(r.body.formStatus.extended.code,'OUTPUT_MISSING');assert.ok(r.body.result.sentence);assert.ok(r.body.result.whems);});
for(const [name,make,code]of [
 ['timeout',()=>{throw Object.assign(Error('PRIVATE TIMEOUT'),{name:'TimeoutError'});},'PROVIDER_TIMEOUT'],
 ['connection',()=>{throw Error('PRIVATE NETWORK');},'PROVIDER_CONNECTION'],
 ['provider envelope',()=>({ok:true,json:async()=>{throw Error('PRIVATE JSON');}}),'PROVIDER_ENVELOPE'],
 ['malformed output',()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:'unparseable private text'}]}]})}),'OUTPUT_JSON'],
 ['empty output',()=>({ok:true,json:async()=>({status:'completed',output:[]})}),'OUTPUT_EMPTY'],
 ['truncated response',()=>({ok:true,json:async()=>({status:'incomplete',incomplete_details:{reason:'max_output_tokens'}})}),'OUTPUT_LIMIT'],
 ['refusal',()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'refusal',refusal:'PRIVATE REFUSAL'}]}]})}),'SAFETY_RESPONSE'],
 ['authentication',()=>({ok:false,status:401}),'PROVIDER_AUTH'],
 ['limit',()=>({ok:false,status:429}),'PROVIDER_LIMIT']])test('Precise failure category: '+name,async()=>{handler._reset();global.fetch=async()=>make();const r=res();await handler(req(input()),r);assert.equal(r.body.code,code);assert.ok(r.body.supportId);assert.ok(!('result' in r.body));assert.ok(!JSON.stringify(r.body).includes('PRIVATE'));});
test('Diagnostic logs contain no prayer, model response, exception text or secret',()=>{assert.ok(logs.length>=9);for(const log of logs){const x=JSON.parse(log);assert.deepEqual(Object.keys(x).sort(),['event','supportId','action','stage','code','elapsedMs'].sort());assert.ok(!log.includes('PRIVATE'));assert.ok(!log.includes('192.0.2'));}});
test('Brand navigation and generation handlers do not rebuild the whole page',()=>{const s=fs.readFileSync(require.resolve('../journey-ui.js'),'utf8');assert.ok(!s.includes('host.render('));assert.ok(!s.includes('location.reload'));assert.ok(!s.includes('window.scrollTo'));});
test('Selected source introduction, Guardrails and 1-line Summary are present without unrelated lesson metadata',()=>{const i=T.content('intro'),g=T.content('guardrails'),s=T.content('summary');assert.match(i,/A simple W.H.E.M.S. prayer pattern/);assert.match(i,/During conflict/);assert.match(i,/Afterwards - thanksgiving/);assert.equal((i.match(/<strong>[WHEMS]:<\/strong>/g)||[]).length,10);assert.match(g,/<h2>Guardrails<\/h2>/);assert.doesNotMatch(g,/Teaching guardrails|One-line teaching summary/);assert.match(s,/<h2>1-line Summary<\/h2>/);assert.match(s,/after His direction becomes clearer/);assert.doesNotMatch(i+g+s,/Week 8|Kay Arthur|ChatGPT|Adrian/);});
